version: '3.7'
services:
  rabbitmq:
    hostname: localhost
    image: rabbitmq:3.8.18-management
    environment:
      RABBITMQ_DEFAULT_USER: demo
      RABBITMQ_DEFAULT_PASS: demo
    ports:
      - "5672:5672"
      - "15672:15672"